export interface User { id: number; email: string; password?: string; firstName?: string | null; lastName?: string | null; mustChangePassword: boolean; isArchived: boolean; roleId: number; createdAt: Date; updatedAt: Date; }
export interface Role { id: number; name: string; createdAt: Date; }
export interface Permission { id: number; key: string; name: string; }
export interface RolePermission { id: number; roleId: number; permissionId: number; enabled: boolean; createdAt: Date; }
export interface Buyer { id: number; name: string; email: string; phone: string; address?: string; gstin?: string; addressLine1?: string; addressLine2?: string; area?: string; city?: string; state?: string; country?: string; postalCode?: string; }
export interface Supplier { id: number; name: string; email: string; phone: string; address?: string; addressLine1?: string; addressLine2?: string; area?: string; city?: string; state?: string; country?: string; postalCode?: string; }
export interface Product { id: number; sku: string; title: string; description?: string | null; category?: string | null; price: number; stock: number; supplierId?: number | null; createdAt: Date; hsnCode?: string | null; taxType?: string | null; taxRate?: number | null; }
export interface InvoiceItem { id: number; title: string; description?: string | null; qty: number; price: number; gst: number; discountPct: number; amount: number; invoiceId: number; productId?: number | null; hsnCode?: string | null; }
export interface Invoice { id: number; invoiceNo: string; buyerId: number; supplierId?: number | null; paymentMethod?: string | null; total: number; serviceCharge: number; balance: number; status: string; createdAt: Date; updatedAt: Date; invoiceDate?: Date; dueDate?: Date; items?: InvoiceItem[]; buyer?: Buyer; supplier?: Supplier | null; }
